# conda env create -f environment.yml
name: diff_hysteresis
channels:
  - conda-forge
dependencies:

  - ipykernel
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.13
  - scipy
  - pip:
    - botorch==0.15.1
    - gpytorch==1.14
    - pygmsh>=7.1.17
    - torch>=2.8.0
    
